%% ECSE 6180 Homework 5
%% Glory Justin 11/23/2020
%% Problem 1
% The mass of air streaming through the rotor in 1 sec is
% 
% $$m = \rho A\frac{(v_1+v_2)}{2}$$
% 
% The power extracted from the wind by the rotor is
% 
% $$P = \frac{1}{2}m(v_1^2-v_2^2)$$
% 
% Substituting for m gives
% 
% $$P = \frac{\rho}{4} A (v_1^2-v_2^2)(v_1+v_2)$$
% 
% The total power in the undisturbed wind streaming through exactly the same 
% area with no rotor blocking the wind is
% 
% $$P_0 = \frac{\rho}{2}Av_1^3$$
% 
% Dividing P by Po
% 
% $$\frac{P}{P_0} = \frac{1}{2}\left(1+\frac{v_2}{v_1}\right)\left[1-\left(\frac{v_2}{v_1}\right)^2\right]$$
% 
% Differentiating w.r.t. (V2/V1) and equating zero shows that the max of this 
% value occurs at V2/V1= 1/3
% 
% $$P_{max} = \frac{1}{2}\left(1+\frac{1}{3}\right)\left(1-\frac{1}{9}\right)P_0 
% \\= \frac{16}{27} A \frac{\rho}{2}v_1^3$$
%% Problem 2
% At the tip, the pitch blade angle is
% 
% $$\theta_{tip} = \tan^{-1}(8/1) + 6^o = 82.22 + 6 = 88.88\text{ degrees}$$
% 
% At the midpoint, the pitch blade angle is
% 
% $$\theta_{mid} = \tan^{-1} (4/1) + 6 = 75.96 + 6 = 81.96 \text{ degrees}$$
% 
% At the point close to the hub (3m), the pitch blade angle
% 
% $$\theta_{hub} = \tan^{-1} (8\times3/50) + 6 = 25.64 + 6 = 31.64 \text{ degrees}$$
%% Problem 3
% Using the cp_init function, the power coefficient Cp curve is computed as 
% follows

theta = 1;
lambda = 0:0.01:18;
Cp = zeros(1,length(lambda));
for i = 1:length(Cp)
    Cp(i) = cp_init(lambda(i),theta);
end
figure
plot(lambda,Cp)
grid on
xlabel('\lambda') 
ylabel('C_p')
%% Problem 4


Rs = 0.004888;
Xs = 0.09241;
Rr = 0.00549;
Xr = 0.09955;

Np = 2;
wo = 2*pi*60;
Vs = 1.0;

s = -1:0.0005:1;

k = [1 5 10];
Te_all = [];
for kk = 1:3
    
    Rr = k(kk)*0.00549;
        
    denom = (Rs + Rr./s).^2 + (Xs + Xr ).^2;

   Te = (Rr./s)*Vs^2./denom;
    Te_all = [Te_all; Te];
end


figure
plot(s,Te_all(1,:),'b', s,Te_all(2,:),'--r', s,Te_all(3,:),'-.g' )
legend('Rr','5Rr','10Rr')
axis( [ -0.5  0.5  -3  3 ])
hold on
plot( [-99 99],[0 0],'--k')
plot( [ 0 0 ],[-99 99],'--k')
xlabel('Slip (pu)')
ylabel('Torque')
set(gca,'Xdir','reverse')
%% Problem 5
% With a Vr voltage insertion in phase with Vs, the current becomes
% 
% $$I_r = \frac{V_s + V_r - V_r/s}{(R_s + R_r/s) + j(X_s + X_r)$$
% 
% The per-phase electrical torque provided to the generator is the torque provided 
% via the slip and the torque due to the voltage insertion
% 
% $$T_e = |I_r|^2\frac{R_r}{s} + Re\{I_r\frac{V_r+sV_r}{s}\}\\= \frac{(V_s-V_r/s)\left(V_sR_r+R_sV_r(1+s)\right)/s}{(R_s+R_r/s)^2+(X_s+X_r)^2}$$
% 
% Then the three phase torque becomes
% 
% $$T_{e,3phase} = \frac{3N_p}{2}\frac{(V_s-V_r/s)\left(V_sR_r+R_sV_r(1+s)\right)/s}{(R_s+R_r/s)^2+(X_s+X_r)^2}$$
%% Problem 6
% The aggregate model can be determined using the ctive and reactive power losses.
% 
% $$S_{loss,1} = I_1^2Z_1 = I^2Z_1\\S_{loss,2} = (I_1+I_2)^2Z_2 = 4I^2Z_2\\S_{loss,3} 
% = (I_1+I_2+I_3)^2Z_3 = 9I^2Z_3\\S_{loss,4} = (I_1+I_2+I_3+I_4)^2Z_4 = 16I^2Z_4\\S_{loss,total} 
% = I^2Z_1 + 4I^2Z_2 + 9I^2Z_3 + 16I^2Z_4\\= I^2\left(Z_1+4Z_2+9Z_3+16Z_4\right)\\\text{But 
% } I_s = I_1 + I_2 + I_3 + I_4 = 4I\\\text{Thus } S_{loss,total} = \frac{I_s^2}{16}\left(Z_1+4Z_2+9Z_3+16Z_4\right)\\$$
% 
% From the above, the radial connection of the 4 wind turbines can be represented 
% by the aggregate model
% 
% $$S_{loss} = I_sZ_s\\\text{where } Z_s = \frac{1}{16}\left(Z_1+4Z_2+9Z_3+16Z_4\right)$$
%% Problem 7

H_t = 4.06; H_g = 0.58;
D_shaft = 1.5; K_shaft = 130.69;

P_mech = 1.0; P_gen = 1.0;
w_o = 1.2;
%% 
% To determine the torsional mode, we compute the A-matrix and find its eigenvalues

A = ...
  [ -(D_shaft+P_mech/w_o^2)/(2*H_t)   D_shaft/(2*H_t) -K_shaft/(2*H_t); ...
    D_shaft/(2*H_g)   -(D_shaft - P_gen/w_o^2)/(2*H_g)   K_shaft/(2*H_g); ...
    1   -1    0];
eig(A)
%% 
% The oscillatory mode of A is -0.4823 +/- j11.33471 with frequency in Hz

torsional_frequency = 11.3347/(2*pi)
%% 
% The steady-state shaft twist between the turbine and generator is 

delta_tg = (1/K_shaft)*(P_gen/w_o) % 0.0064 rad
%% Problem 8
% (a) For a wind gust response, the wind gust drops from 14m/sec to 8 m/sec, 
% then goes back to 14 m/sec. The following plots were generated by changing wmag 
% to -6. As the wind speed begins to drop at 5 sec, the mechanical power and speeds 
% also drop. The terminal voltage starts to rise and the pitch controller starts 
% to reduce the pitch angle to extract more power from the wind. As the wind speed 
% drops below 12, the pitch controller saturates at 0 degrees. The wind speed 
% begins to increase with the angle still at 0, so the Pmech exceeds its rating 
% and the pitch controller increases the angle to return the system to its original 
% operating condition.
% 
% 
% 
% (b) By changing wmag to 4, the following plots were generated. The wind gust 
% goes up from 14 m/sec to 18 m/sec then drops back to 14 m/sec. As the wind speed 
% begins to increase at 5 sec, the mechanical power and speeds also increase. 
% The terminal voltage starts to drop and the pitch controller starts to increase 
% the pitch angle to reduce the Pmech. As the wind speed reaches 18, the Pmech 
% begins to drop and the turbine speed also drops until 10 sec when the gust ends. 
% Then the system returns to its original operating condition.
% 
% 
% 
% (c) For a 200 msec fault at bus 5 starting at 1 sec, the following plots were 
% generated. The fault causes the generator power output to drop until it is cleared. 
% While the fault lasts, the rotor speed increases causing the pitch angle to 
% increase in order to reduce the power extracted. The torsional oscillation is 
% also visible. The fault is cleared before the critical clearing time so the 
% system returns to its initial operating conditions thus remaining stable. 
% 
% 
% 
% (d) Leaving the fault for 2 sec generates the following plots. The fault disrupts 
% the system and causes the power to drop significantly. Due to the duration of 
% the fault, the system has difficulty returning to normal operating conditions 
% so it goes unstable.
% 
% 
% 
% (e) For a step decrease in the voltage at the infinite bus, the following 
% results were obtained. As the terminal voltage is reduced, the mechanical power 
% and pitch angle are disturbed slightly. The reactive power output increases 
% slightly, but the system returns to initial operating conditions with a decrease 
% in terminal voltage.
% 
%